# Render設定ファイル
services:
  - type: web
    name: social-insurance-news
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application
    plan: free
    region: oregon
    branch: main
    
    # 環境変数
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production
      - key: TZ
        value: Asia/Tokyo
      - key: OPENAI_API_KEY
        sync: false  # Renderダッシュボードで設定
      - key: I_MOBILE_SITE_ID
        sync: false  # 広告設定
      - key: ZUCKS_SITE_ID  
        sync: false  # 広告設定
    
    # ヘルスチェック
    healthCheckPath: /health
    
    # 自動デプロイ設定
    autoDeploy: true

# 注意: cronジョブはGitHub Actionsで実行
# .github/workflows/social-insurance-news-update.yml を参照